#!/usr/bin/python3

import socket
import sys
from _thread import *
import select 
import re 

if len(sys.argv)!=3:
    print("Valid input format is ./chatclient ip:port nickname")
    sys.exit()

server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
information = (sys.argv[1])
agent=information.split(':')
ipaddress=str(agent[0])
port=int(agent[1])
nick=str(sys.argv[2])
server_socket.connect((ipaddress, port))
first_msg=server_socket.recv(2048).decode('utf-8')
print(first_msg)
nick = 'NICK ' + nick
server.sendall(nick.encode('utf-8'))
ok_msg=server.recv(2048).decode('utf-8')
print(ok_msg)
if ok_msg == "OK":
    pass
elif ok_msg == "ERR malformed nick name":
    print('write a nick name upto 12 characters without special characters')
    print('try again with valid nickname, disconnected for now')
    sys.exit()
